<?php
$max=Mage::getModel('catalog/layer_filter_price');
$maxPrice=$max->getMaxPriceInt();
$maxPrice++;

$minPrice= Mage::getSingleton('catalog/layer')
    ->setCurrentCategory(Mage::registry('current_category'))
    ->getProductCollection()
    ->getMinPrice();
$minPrice=number_format($minPrice,0);
$minPrice--;
$currency= str_replace('.','',str_replace('0','', Mage::helper('core')->currency('')));
$currency_symbol=Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol();
if($maxPrice!=1):
?>
<div class="block">
    <div class="block-title"><strong><span><?php echo $this->__('Price') ?></span></strong></div>
    <div class="block-content">
        <div id="price_slider_wrapper">
            <div class="noUiSlider" id="noUiSlider">
                <div class="noUi-handle noUi-lowerHandle"></div>
                <div class="noUi-midBar"></div>
                <div class="noUi-handle noUi-upperHandle"></div>
            </div>
            <div id="valueInput"></div>
            <div class="price_range">
                <div id="price_from"><?php echo $currency_symbol.''.$minPrice?></div>
                <div id="price_to"><?php echo $currency_symbol.''.$maxPrice?></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    jQuery(function(){

        function addParameter(url, parameterName, parameterValue, atStart/*Add param before others*/){
            replaceDuplicates = true;
            if(url.indexOf('#') > 0){
                var cl = url.indexOf('#');
                urlhash = url.substring(url.indexOf('#'),url.length);
            } else {
                urlhash = '';
                cl = url.length;
            }
            sourceUrl = url.substring(0,cl);


            var urlParts = sourceUrl.split("?");
            var newQueryString = "";

            if (urlParts.length > 1)
            {
                var parameters = urlParts[1].split("&");
                for (var i=0; (i < parameters.length); i++)
                {
                    var parameterParts = parameters[i].split("=");
                    if (!(replaceDuplicates && parameterParts[0] == parameterName))
                    {
                        if (newQueryString == "")
                            newQueryString = "?";
                        else
                            newQueryString += "&";
                        newQueryString += parameterParts[0] + "=" + (parameterParts[1]?parameterParts[1]:'');
                    }
                }
            }
            if (newQueryString == "")
                newQueryString = "?";

            if(atStart){
                newQueryString = '?'+ parameterName + "=" + parameterValue + (newQueryString.length>1?'&'+newQueryString.substring(1):'');
            } else {
                if (newQueryString !== "" && newQueryString != '?')
                    newQueryString += "&";
                newQueryString += parameterName + "=" + (parameterValue?parameterValue:'');
            }
            return urlParts[0] + newQueryString + urlhash;
        };

        jQuery("#noUiSlider").empty().noUiSlider( 'init', {
            scale:[<?php echo $minPrice?>,<?php echo $maxPrice?>],
            start:[<?php echo $minPrice?>,<?php echo $maxPrice?>],
            change:
                function(){
                    var values = jQuery(this).noUiSlider( 'value' );
                    jQuery('#price_from').text('<?php echo $currency_symbol?>'+values[0]);
                    jQuery('#price_to').text('<?php echo $currency_symbol?>'+values[1]);

                },
            end:
                function(type){
                    var values = jQuery(this).noUiSlider( 'value' );
                    price_val=values[0]+'-'+values[1];
                    setLocation(addParameter('<?php echo Mage::helper("core/url")->getCurrentUrl()?>','price',price_val));
                }

        });
    });
</script>
<?php endif;?>