<?php if ($_productCollection=$this->getLoadedProductCollection()): ?>
    <?php foreach ($_productCollection as $_product): ?>
    <?php  if(!$_product->isSaleable() && !Mage::getStoreConfig('cataloginventory/options/show_out_of_stock'))continue; ?>
    <?php
     $widthBig=283;
            $heightBig=343;
    $price=$this->getPriceHtml($_product, true);
    $izotope=true;
    ?>
    <?php
    /*
     * Product Preview HTML  is using in many blocks (category listing, shortcodes).
     * That is why Product Preview HTML generation collected in one function drawProductPreview()
     * You can edit this function  in file \app\code\local\Etheme\Megatronconfig\Helper\Data.php
    */
    ?>
    <?php  echo Mage::helper('megatronconfig')->drawProductPreview($_product,$this,$widthBig,$heightBig,$price,false,'',true, $izotope, $this->getCategoryId())?>
    <?php endforeach ?>
<?php endif; ?>